package com.myweb.pojo;

public class Usertomenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertomenu.id
     *
     * @mbg.generated Mon Mar 12 14:24:27 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertomenu.shuxingid
     *
     * @mbg.generated Mon Mar 12 14:24:27 CST 2018
     */
    private Integer shuxingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertomenu.menuid
     *
     * @mbg.generated Mon Mar 12 14:24:27 CST 2018
     */
    private Integer menuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertomenu.id
     *
     * @return the value of usertomenu.id
     *
     * @mbg.generated Mon Mar 12 14:24:27 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertomenu.id
     *
     * @param id the value for usertomenu.id
     *
     * @mbg.generated Mon Mar 12 14:24:27 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertomenu.shuxingid
     *
     * @return the value of usertomenu.shuxingid
     *
     * @mbg.generated Mon Mar 12 14:24:27 CST 2018
     */
    public Integer getShuxingid() {
        return shuxingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertomenu.shuxingid
     *
     * @param shuxingid the value for usertomenu.shuxingid
     *
     * @mbg.generated Mon Mar 12 14:24:27 CST 2018
     */
    public void setShuxingid(Integer shuxingid) {
        this.shuxingid = shuxingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertomenu.menuid
     *
     * @return the value of usertomenu.menuid
     *
     * @mbg.generated Mon Mar 12 14:24:27 CST 2018
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertomenu.menuid
     *
     * @param menuid the value for usertomenu.menuid
     *
     * @mbg.generated Mon Mar 12 14:24:27 CST 2018
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }
}